version: '3'
services:
  rabbit:
    image: rabbitmq
    ports:
     - "5672:5672"
  mail:
    build:
      context: email-client/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on: 
      - rabbit
    links:
      - rabbit
  analytics:
    build:
      context: analytics/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
  leads:
    build:
      context: lead-check/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
  task-manager:
    build:
      context: task-manager/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit