version: '3'
services:
  rabbit:
    image: rabbitmq
    ports:
     - "5672:5672"
  mail:
    build:
      context: email-client/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on: 
      - rabbit
    links:
      - rabbit
  analytics:
    build:
      context: analytics/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
  leads:
    build:
      context: lead-check/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example